### ISSUE TITLE
Connect with API Django

### ISSUE THREAD

**Issue by congtoanle** [vvv-v13/nuxt-jwt-starter#1]
I use Django for building backend. How can I fix this API file: https://github.com/vvv-v13/nuxt-jwt-starter/blob/master/api/index.js in order to sign in by using username and password in Django. Thank you

**Comment by vvv-v13** [comment]
Hi, this file  is example API,   if you want to use django backend you need to change backendUrl in https://github.com/vvv-v13/nuxt-jwt-starter/blob/master/store/index.js

**Comment by congtoanle** [comment]
I tried but when I reload page (F5), it haven't remain logged in

**Comment by vvv-v13** [comment]
I fixed typo, please try again

**Comment by congtoanle** [comment]
Do I need to change https://github.com/vvv-v13/nuxt-jwt-starter/blob/master/api/index.js?

**Comment by vvv-v13** [comment]
You don't need this file, you have django backend

**Comment by congtoanle** [comment]
Thank you. It works perfectly! Stars for your project!
