### ISSUE TITLE
How to set unlimited expired time Token Auth?

### ISSUE THREAD

**Issue by feedgit** [vvv-v13/nuxt-jwt-starter#2]
How can I adjust this file https://github.com/vvv-v13/nuxt-jwt-starter/blob/master/store/index.js to set unlimited expired time Token

**Comment by vvv-v13** [comment]
Hi, you can modify token expire in 54-th line
replace:
Cookie.set('token', data.token, { expires: 1 / 24 * 6 });  // Expire for 6h      

like :
Cookie.set('token', data.token);  // Without Expire

**Comment by congtoanle** [comment]
I tried but not success. It expired about 5 minutes.

**Comment by vvv-v13** [comment]
Hi, you need modify you django backend

https://getblimp.github.io/django-rest-framework-jwt/


JWT_EXPIRATION_DELTA
This is an instance of Python's datetime.timedelta. This will be added to datetime.utcnow() to set the expiration time.

Default is datetime.timedelta(seconds=300)(5 minutes).

**Comment by congtoanle** [comment]
Thank you, I think maybe I use Refresh Token to maintain logged in in stead of setting JWT_EXPIRATION_DELTA for a long time
